select soc_name,case_status ,count(soc_name) as cnt from h1b_applications where job_title like '%DATA SCIENTIST%' and case_status = 'CERTIFIED' group by soc_name,case_status order by cnt desc;



-----------------------------------------------------------------------------------------------------------

STATISTICIANS								CERTIFIED	572
COMPUTER AND INFORMATION RESEARCH SCIENTISTS				CERTIFIED	419
OPERATIONS RESEARCH ANALYSTS						CERTIFIED	380
Computer and Information Research Scientists				CERTIFIED	181
COMPUTER OCCUPATIONS, ALL OTHER						CERTIFIED	160
MATHEMATICIANS								CERTIFIED	144
Statisticians								CERTIFIED	133
SOFTWARE DEVELOPERS, APPLICATIONS					CERTIFIED	124
COMPUTER SYSTEMS ANALYSTS						CERTIFIED	123
Operations Research Analysts						CERTIFIED	104
SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE					CERTIFIED	51
Software Developers, Applications					CERTIFIED	50
Computer Occupations, All Other						CERTIFIED	43
Computer Systems Analysts						CERTIFIED	25
BIOLOGICAL SCIENTISTS, ALL OTHER					CERTIFIED	24
Software Developers, Systems Software					CERTIFIED	18
Database Administrators							CERTIFIED	16
MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS			CERTIFIED	12
NA									CERTIFIED	11
MATHEMATICAL TECHNICIANS						CERTIFIED	10
Mathematicians								CERTIFIED	10
FINANCIAL SPECIALISTS, ALL OTHER					CERTIFIED	9
COMPUTER AND INFORMATION SYSTEMS MANAGERS				CERTIFIED	9
ECONOMISTS								CERTIFIED	7
Biological Scientists, All Other					CERTIFIED	7
MANAGEMENT ANALYSTS							CERTIFIED	7
Market Research Analysts and Marketing Specialists			CERTIFIED	6
DATABASE ADMINISTRATORS							CERTIFIED	6
COMPUTER PROGRAMMERS							CERTIFIED	5
ENGINEERS, ALL OTHER							CERTIFIED	4
ELECTRICAL ENGINEERS							CERTIFIED	4
CIVIL ENGINEERS								CERTIFIED	3
FINANCIAL ANALYSTS							CERTIFIED	3
INDUSTRIAL-ORGANIZATIONAL PSYCHOLOGISTS					CERTIFIED	3
INDUSTRIAL ENGINEERS							CERTIFIED	3
Computer Software Engineers, Applications				CERTIFIED	3
Computer and Information Systems Managers				CERTIFIED	3
CLINICAL DATA MANAGERS							CERTIFIED	3
Computer Programmers							CERTIFIED	3
COMPUTER PROGRAMMERS, R&D						CERTIFIED	2
CREDIT ANALYSTS								CERTIFIED	2
ASTRONOMERS								CERTIFIED	2
COMPUTER NETWORK ARCHITECTS						CERTIFIED	2
BUSINESS INTELLIGENCE ANALYSTS						CERTIFIED	2
Computer and Information Scientists, Research				CERTIFIED	2
Credit Analysts								CERTIFIED	2
LOGISTICIANS								CERTIFIED	2
Economists								CERTIFIED	2
SURVEY RESEARCHERS							CERTIFIED	2
Electrical Engineers							CERTIFIED	2
MATHEMATICAL SCIENCE OCCUPATIONS, ALL OTHER				CERTIFIED	2
Management Analysts							CERTIFIED	2
SALES ENGINEERS								CERTIFIED	2
Social Scientists and Related Workers, All Other			CERTIFIED	1
STATISTICAL ASSISTANTS							CERTIFIED	1
SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE, NON R&D				CERTIFIED	1
NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS				CERTIFIED	1
NATURAL SCIENCES MANAGERS						CERTIFIED	1
Medical Scientists, Except Epidemiologists				CERTIFIED	1
MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS				CERTIFIED	1
MATERIALS ENGINEERS							CERTIFIED	1
Life Scientists, All Other						CERTIFIED	1
GEOSPATIAL INFORMATION SCIENTISTS AND TECHNOLOGIS		T	CERTIFIED	1
GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAPHERS			CERTIFIED	1
Financial Specialists, All Other					CERTIFIED	1
Financial Analysts							CERTIFIED	1
Chemical Engineers							CERTIFIED	1
COMPUTER & INFORMATION RESEARCH SCIENTIST				CERTIFIED	1
CHEMICAL ENGINEERS							CERTIFIED	1
Survey Researchers							CERTIFIED	1
SOFTWARE DEVELOPERS, APPLICATIONS, R&D					CERTIFIED	1
SOCIAL SCIENCE RESEARCH ASSISTANTS					CERTIFIED	1
PHYSICISTS								CERTIFIED	1
Materials Scientists							CERTIFIED	1
MECHANICAL ENGINEERS							CERTIFIED	1
MATERIALS SCIENTISTS							CERTIFIED	1
Logisticians								CERTIFIED	1
INFORMATION SECURITY ANALYSTS						CERTIFIED	1
Financial Examiners							CERTIFIED	1
Engineers, All Other							CERTIFIED	1
Computer Network Architects						CERTIFIED	1
COMPUTER SYSTEMS ANALYST						CERTIFIED	1
COMPUTER & INFORMATION RESEARCH SCIENTISTS				CERTIFIED	1
BIOMEDICAL ENGINEERS							CERTIFIED	1
ACTUARIES								CERTIFIED	1
Time taken: 121.42 seconds, Fetched: 85 row(s)
